name       : libshumate
version    : 1.0.4
release    : 3
source     :
    - https://download.gnome.org/sources/libshumate/1.0/libshumate-1.0.4.tar.xz : ad685d9c49d24ba4e16c55e32aa86abd5a22b8bb08171204ed319bdd6d156125
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Shumate is a GTK toolkit providing widgets for embedded maps.
description: |
    Shumate is a GTK toolkit providing widgets for embedded maps.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(sqlite3)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
