name       : libshumate
version    : 1.0.1
release    : 1
source     :
    - https://download.gnome.org/sources/libshumate/1.0/libshumate-1.0.1.tar.xz : 1e264fa8a1dfa5914f243e2efc64c69e341429ae8537c5eaa9aebb5007cda151
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Shumate is a GTK toolkit providing widgets for embedded maps.
description: |
    Shumate is a GTK toolkit providing widgets for embedded maps.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(sqlite3)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
